packaging-tutorial: packaging-tutorial.pdf

packaging-tutorial.pdf: packaging-tutorial.tex
	pdflatex packaging-tutorial.tex
	pdflatex packaging-tutorial.tex

clean:
	@${RM} *.aux *.log *.nav *.out *.snm *.toc *.vrb *.pdf

.PHONY: clean
